### ISSUE TITLE
Add option to force timestamps when logging

### ISSUE THREAD

**Issue by Croq360** [wouterdebie/locast2tuner#31]
Currently, the logging I'm getting doesn't appear to have any timestamps.  It would be helpful to have that so if something goes wrong, you know when it happened, and also, to be able to look at it and see that you have recent entries.

**Comment by Croq360** [comment]
This is an enhancement request, but I can't figure out how to flag it as such.

**Comment by wouterdebie** [comment]
What locast2tuner (and locast2dvr as well) does is that if you start it from the command line and have a terminal (or tty in UNIX), it will display the timestamp. If it doesn't have a tty (because it's piped to another process, or the output is handled by syslog), it will remove the timestamp, because otherwise the timestamp will be in the log file twice. I could add an option to always show the timestamp.

**Comment by Croq360** [comment]
Yeah, something like that would be good.  I tried to set the logging in WinSW (that I'm using to run locast2tuner as a service) to do the timestamps, but it doesn't appear to be capable of adding them.

**Comment by wouterdebie** [comment]
Interesting.. I'll add the option!
