### ISSUE TITLE
Merging M3U lists

### ISSUE THREAD

**Issue by gedster314** [wouterdebie/locast2tuner#50]
I think a nice feature would be the ability to append other m3u lists to the tuner.m3u list.  Maybe have the ability to enter web addresses to pull m3u you files from and merge them into the tuner.m3u.  As an example I would like to pull this in and append it to the tuner.m3u.

https://iptv-org.github.io/iptv/languages/eng.m3u
--

<br class="Apple-interchange-newline">

**Comment by wouterdebie** [comment]
Interesting idea.. However, I'm not sure if I want to do this, since this is not related to locast per se. I don't want locast2tuner to become a "everything-to-tuner". Most of the logic is on the locast side and the fact that you can access it as an m3u is merely a side-effect. There are other projects that could probably merge them or support multiple sources (like https://github.com/fHDHR/fHDHR)
