### ISSUE TITLE
Help for installations ?

### ISSUE THREAD

**Issue by teleflix** [wouterdebie/locast2tuner#63]
Hello :)

guy i am trying to install script but almost sure i am doing something worng :(, i have one PC( server) with Ubuntu 14.04 and i am follow this : 

# Add the PPA key
$ curl -s "https://wouterdebie.github.io/ppa/KEY.gpg" | sudo apt-key add -
# Add the locast2tuner repository
$ sudo curl -o /etc/apt/sources.list.d/locast2tuner.list "https://wouterdebie.github.io/ppa/sources.list"
$ sudo apt update
# Install locast2tuner
$ sudo apt install locast2tuner

but is not working , some suggestion?

thank in advance

**Comment by eiddor** [comment]
@teleflix Can you be a little clearer about what exactly is not working?  Which command fails and what is the message?

I don't believe we're pushing the packages to the older versions of Ubuntu, so you will probably have to build this manually.

Also, Ubuntu 14.04 has been end of support for 2 years and hasn't had any patches or fixes since then.

**Comment by wouterdebie** [comment]
Yes, given that Ubuntu 14.04 is 7 years old, there's no support for it.

**Comment by teleflix** [comment]
Hi thanks a lot for respond me :) ok i will install in afew minutes Ubuntu 18 or ubunto 20 :)
