### ISSUE TITLE
Won't start on Ubuntu 20 after recent update

### ISSUE THREAD

**Issue by dgiffen** [wouterdebie/locast2tuner#79]
*NOTE THAT UNCLEAR BUG REPORTS (i.e. without the information requested below like Aug 16 07:08:39.771 INFO locast2tuner 0.1.52 on Linux 5.4.0-81-generic starting..
Aug 16 07:08:39.771 INFO UUID: 7151e129-3bdf-46b1-81f4-aab466850ef1
Aug 16 07:08:39.772 INFO Logging in with USERNAME
Aug 16 07:08:40.014 INFO Login succeeded!
Aug 16 07:08:40.412 INFO Using cached FCC facilities at /var/lib/locast2tuner/facilities
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `transcodeId`", line: 1, column: 242015) }', src/service/mod.rs:329:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

**Comment by RandomNinjaAtk** [comment]
`Aug 16 08:01:09.508 INFO Cached FCC facilities to /root/.locast2tuner/facilities
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `transcodeId`", line: 1, column: 218065) }', src/service/mod.rs:329:10`
Also seeing the same thing...

**Comment by dgiffen** [comment]
my issue began with the most recent update to the Ubuntu packages.

**Comment by johnluber** [comment]
I'm seeing the same on my system as well.  Running Ubuntu 20.04 with updates applied yesterday.

**Comment by danlo315** [comment]
Filling this out as a bug report (I'm running on docker, same issue):

*NOTE THAT UNCLEAR BUG REPORTS (i.e. without the information requested below like logs, settings, versions, etc) MIGHT BE CLOSED WITHOUT ANY HELP!!*

**Describe the bug**
thread 'main' panic, started around 5am Eastern

thread 'main' panicked at 'slog-scope: No logger set. Use `slog_scope::set_global_logger` or `slog_scope::scope`.', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.4.0/lib.rs:125:13,
stack backtrace:,
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.,
   0: std::panicking::begin_panic

**To Reproduce**
Steps to reproduce the behavior:
Starting/restarting docker container with latest image


** Logs **
  10: tokio::macros::scoped_tls::ScopedKey<T>::set,
  11: tokio::runtime::Runtime::block_on,
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.,
Aug 16 13:25:43.150 INFO locast2tuner 0.1.52 on Linux 4.15.0-50-generic starting..,
Aug 16 13:25:43.150 INFO UUID: 60e30119-1f04-4661-8b68-1998e028638e,
Aug 16 13:25:43.150 INFO Logging in with me@danlo.org,
config selected = /app/config/config ,
Aug 16 13:25:43.163 DEBG starting new connection: https://api.locastnet.org/,
Aug 16 13:25:43.407 DEBG response '200 OK' for https://api.locastnet.org/api/user/login?client_id=CqhAMsBw%2BnxTXSJMLGqyOw%3D%3D,
Aug 16 13:25:43.407 INFO Login succeeded!,
Aug 16 13:25:43.419 DEBG starting new connection: https://api.locastnet.org/,
Aug 16 13:25:43.617 DEBG response '200 OK' for https://api.locastnet.org/api/user/me,
Aug 16 13:25:43.627 DEBG starting new connection: https://api.locastnet.org/,
Aug 16 13:25:43.799 DEBG response '200 OK' for https://api.locastnet.org/api/dma,
Aug 16 13:25:43.802 INFO Using cached FCC facilities at /root/.locast2tuner/facilities,
Aug 16 13:25:43.823 DEBG starting new connection: https://api.locastnet.org/,
Aug 16 13:25:43.835 DEBG starting new connection: https://api.locastnet.org/,
Aug 16 13:25:44.010 DEBG response '200 OK' for https://api.locastnet.org/api/watch/dma/zip/10019,
Aug 16 13:25:44.034 DEBG starting new connection: https://api.locastnet.org/,
Aug 16 13:25:44.036 DEBG response '200 OK' for https://api.locastnet.org/api/watch/dma/zip/30360,
Aug 16 13:25:44.047 DEBG starting new connection: https://api.locastnet.org/,
Aug 16 13:25:44.219 DEBG response '200 OK' for https://api.locastnet.org/api/watch/epg/524?startTime=2021-08-16T00:00:00-00:00&hours=192,
Aug 16 13:25:44.246 DEBG response '200 OK' for https://api.locastnet.org/api/watch/epg/501?startTime=2021-08-16T00:00:00-00:00&hours=192,
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `transcodeId`", line: 1, column: 194739) }', src/service/mod.rs:329:10,
stack backtrace:,
   0: rust_begin_unwind,
             at ./rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panicking.rs:493:5,
   1: core::panicking::panic_fmt,
             at ./rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/core/src/panicking.rs:92:14,
   2: core::result::unwrap_failed,
             at ./rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/core/src/result.rs:1355:5,
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll,
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll,
   5: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll,
   6: <futures_util::future::join_all::JoinAll<F> as core::future::future::Future>::poll,
   7: locast2tuner::main::{{closure}},
   8: tokio::macros::scoped_tls::ScopedKey<T>::set,
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll,
  10: tokio::macros::scoped_tls::ScopedKey<T>::set,
  11: tokio::runtime::Runtime::block_on,

** Configuration **
Add a copy of your config. You can get a copy of your running config by opening /config in a browser (e.g http://localhost:6077/config). This will not expose your locast password. If you can't access /config, please add your config file *without* your password.

**Environment**
Latest docker image (ghcr.io/wouterdebie/locast2tuner:latest)

**Screenshots**
If applicable, add screenshots to help explain your problem.

** Environment**
What operating system and version you are using.

**Additional context**
Add any other context about the problem here.

**Comment by jg-24** [comment]
Same issue on mac running in terminal and installed with brew.

Has been running fine since upgrading to 0.1.52 on Aug 14 and failed last night right at 2AM when it logged back in after the token expiring:

```
Aug 16 02:00:36.343 INFO Login succeeded!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `transcodeId`", line: 1, column: 195683) }', src/service/mod.rs:329:10
```

Restart immediately failed with the same error.

**Comment by wouterdebie** [comment]
0.1.53 has the fix. It's building as I write this and should be ready in 15 mins or so.
